"""Type stubs for rtm2. Auto-generated; do not edit manually."""

from __future__ import annotations

from typing import Any, overload
import queue
import socket
import numpy as np

__version__: str

class StateUpdate:
    parameter: str
    value: object
    def __init__(self, parameter: str, value: object) -> None: ...

class ReadResult:
    updates: list[StateUpdate]
    data: np.ndarray
    raw_data: np.ndarray
    error: None | str
    def __init__(
        self,
        updates: list[StateUpdate],
        data: np.ndarray,
        raw_data: np.ndarray,
        error: None | str = None,
    ) -> None: ...

class PacketFramingError(Exception): ...

class _CmdFacade:
    # Set Averaging Time.
    def avgt(self, arg0: float) -> None: ...
    # Set Current Limit.
    def cpro(self, arg0: float) -> None: ...
    # Set Current Limit.
    def ipro(self, arg0: float) -> None: ...
    # Set Output Voltage Limit.
    def vpro(self, arg0: float) -> None: ...
    # Set AC Frequency.
    def lfrq(self, arg0: float) -> None: ...
    # Set Series Resistance. Negative values enable auto-selection.
    def sres(self, arg0: float) -> None: ...
    # Set Current measurement range. Negative values enable auto-selection.
    def crng(self, arg0: float) -> None: ...
    # Set Output Voltage measurement range. Negative values enable auto-selection.
    def vorg(self, arg0: float) -> None: ...
    # Set Input Voltage measurement range. Negative values enable auto-selection.
    def virg(self, arg0: float) -> None: ...
    # Set AC Phase Shift from Reference Input.
    def phsh(self, arg0: float) -> None: ...
    # Request the timestamp difference between the provided timestamp and the RTM2's internal one.
    def time(self, arg0: float) -> None: ...
    # Set Output Control Mode.
    def cmod(self, arg0: int) -> None: ...
    # Set Waveform Mode.
    def wfmd(self, arg0: int) -> None: ...
    # Detected Analysis Mode.
    def modq(self, arg0: int) -> None: ...
    # Set Analysis Mode.
    def amod(self, arg0: int) -> None: ...
    # Set Multisample Mode.
    def mult(self, arg0: int) -> None: ...
    # Set Reference Multiplexer Input.
    def refm(self, arg0: int) -> None: ...
    # Set Phase Locking Behavior.
    def phlk(self, arg0: int) -> None: ...
    # Set SNS preamplifier Mode.
    def snsa(self, arg0: int) -> None: ...
    # Set BNC Coax Mode.
    def coax(self, arg0: int) -> None: ...
    # Set Drive Polarity Mode.
    def drvp(self, arg0: int) -> None: ...
    # Set Data sample counter. Negative values enable infinite sampling.
    def meas(self, arg0: int) -> None: ...
    # Begin a new demodulation window immediately.
    def trig(self) -> None: ...
    # Begin the pulse train (or arbitrary waveform) generation.
    def puls(self) -> None: ...
    # Request all device settings.
    def gass(self) -> None: ...
    # Clear device side data buffer.
    def cldt(self) -> None: ...
    # Series Resistance Up.
    def srup(self) -> None: ...
    # Series Resistance Down.
    def srdn(self) -> None: ...
    # Current measurement range Up.
    def crup(self) -> None: ...
    # Current measurement range Down.
    def crdn(self) -> None: ...
    # Voltage Output measurement range Up.
    def voru(self) -> None: ...
    # Voltage Output measurement range Down.
    def vord(self) -> None: ...
    # Voltage Input measurement range Up.
    def viru(self) -> None: ...
    # Voltage Input measurement range Down.
    def vird(self) -> None: ...
    # Set Current Amplitude setpoint. Optional 2nd argument: Time to arrival.
    @overload
    def camp(self, arg0: float) -> None: ...
    @overload
    def camp(self, arg0: float, arg1: float) -> None: ...
    # Set Current DC setpoint. Optional 2nd argument: Time to arrival.
    @overload
    def cudc(self, arg0: float) -> None: ...
    @overload
    def cudc(self, arg0: float, arg1: float) -> None: ...
    # Set Voltage Amplitude setpoint. Optional 2nd argument: Time to arrival.
    @overload
    def vamp(self, arg0: float) -> None: ...
    @overload
    def vamp(self, arg0: float, arg1: float) -> None: ...
    # Set Voltage DC setpoint. Optional 2nd argument: Time to arrival.
    @overload
    def vodc(self, arg0: float) -> None: ...
    @overload
    def vodc(self, arg0: float, arg1: float) -> None: ...
    # Set DIO0 mode.
    def dio0(self, arg0: int, arg1: float) -> None: ...
    # Set DIO1 mode.
    def dio1(self, arg0: int, arg1: float) -> None: ...
    # Define Switch Matrix states.
    def swit(self, *args: int) -> None: ...
    # Set indices of data channels that will be sent as reply to `newd` calls.
    def selc(self, *args: int) -> None: ...
    # Set pulse parameter array entries.
    def puar(self, *args: float) -> None: ...
    # Request all new data rows, i.e. previously unsent rows.
    def newd(self) -> None: ...
    # Request all data rows.
    def alld(self) -> None: ...
    # Request a number of rows of raw ADC samples.
    def rawd(self, arg0: int) -> None: ...

def SwitState(DRVn: list, DRVp: list, SNSn: list, SNSp: list) -> int: ...
def Discover(
    timeout: float = 12.0,
    primer_addrs: list[str] | None = None,
    primer_port: int = 61556,
    verbose: bool = False,
) -> dict[str, str]: ...

class RTM2:
    host: str
    port: int
    tcp: socket.socket | None
    cmd: _CmdFacade

    def __init__(self, host: str, port: int, timeout: float = 1.0) -> None: ...
    def __enter__(self) -> RTM2: ...
    def __exit__(self, exc_type: Any, exc_val: Any, traceback: Any) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def get_state(self) -> dict[str, object]: ...
    def send(self, cmd: str, *pars: object) -> None: ...
    def write(self, usrstr: str) -> None: ...
    def read(self, max_packets: int = 100) -> ReadResult: ...
    def read_until(
        self,
        *terms: str,
        timeout: float = 10.0,
        listen: float = 0.0,
        send: str | tuple[Any, ...] | list[Any] | None = None,
    ) -> ReadResult: ...

class RTM2Reader:
    rtm: RTM2
    results: queue.Queue[ReadResult | Exception]
    def __init__(self, rtm: RTM2) -> None: ...
    def start(self) -> None: ...
    def stop(self, timeout: float | None = 2.0) -> None: ...
    def _run(self) -> None: ...
